# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='longitude',
        ),
    ]
