# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170914_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_lat', models.FloatField()),
                ('w_long', models.FloatField()),
                ('well_water_depth', models.FloatField()),
                ('avg_wateryield', models.FloatField()),
                ('F_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='wellyield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_depth', models.FloatField()),
                ('date', models.DateField(null=True)),
                ('wateryield', models.FloatField()),
                ('well_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Well')),
            ],
        ),
    ]
